### PR TITLE
expanding qctrl.m with elementary controllers 

### PR DESCRIPTION
**Pull request by iftahnaf**
adding lag, notch, PID, and poles/zeros objects to qctrl.m.

### CODE REVIEW

**Comment by rubindan** [comment]
The methods `Qpz`, `PID`, `parallel`, and `notch` are meant to be called directly by the user, and therefore must include detailed inline help as `lag` and 'lead'  has. Please also change their names to lower case.  

I do not understand why you changed 'lead' so that it always requires 3 input arguments. Please use the former syntax where 3rd argument is only needed for a 2nd order element. If you need to, use `inputParser` (or any other method) to allow calling with a third argument equal `-1`  for a 1st order. 

Please allow `pid` to be called without all 8 inputs. For example if only a PI is wanted: `qctrl.pid(kp,ki)`

**Comment by iftahnaf** [comment]
Hi @rubindan,

I added inline detailed help in the missing controllers, and change the Qpz and PID to lower case.

I changed the lead controller syntax so now it can work with 2 inputs for 1st order and 3 inputs for 2nd order (or first if damping is -1)

PID now works with different numbers of inputs.

Let me know if there are more things to fix.

**Comment by rubindan** [comment]
Thank you for the corrections. Just another comment: I think standard PID should be a separate function. That way you have `qctrl.pid(Kp,Ki,Kd,Tf)` and  `qctrl.pidstd(Kp,Ti,Td,N)`. There is no point in having a single function with 8 input arguments. It is also more consistent with the Control System Toolbox, which includes `pid` and `pidstd`.

**Comment by iftahnaf** [comment]
Hi @rubindan,

I made  `pidstd` qctrl object and edit the `pid` qctrl object as you suggested.
The loop shaping GUI works with those updates.

**Pull request merged**
